### PR TITLE
Famousgrumblecakes english 1 1

### PR DESCRIPTION
**Pull request by famousgrumblecakes**

### CODE REVIEW

**Comment by dead2me** [comment]
beeper module?

**Comment by famousgrumblecakes** [comment]
@dead2me if you comment it out, it works. Beeper included.

#import beeper

**Comment by dead2me** [comment]
Thank you worked! I was hoping to get some advice. I think my GPIO setting are a bit messed up as when I run 'attendance.py' I get this error:

attendance.py:178: RuntimeWarning: No channels have been set up yet - nothing to clean up!  Try cleaning up at the end of your program instead!
  GPIO.cleanup()
attendance.py:174: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(8, GPIO.OUT)
06.03.2015 21:02:31
06.03.2015 21:02:32
06.03.2015 21:02:33
attendance.py:196: RuntimeWarning: No channels have been set up yet - nothing to clean up!  Try cleaning up at the end of your program instead!
  GPIO.cleanup()

I'll keep troubleshooting; but, if you could help point me in the right direction that would be amazing.
Thank you

**Comment by famousgrumblecakes** [comment]
@dead2me when I was having a similar problem, I pressed 5 twice to put it into the reading now. On the instructable,  somewhere it mentions different modes you can put it into haha. If that doesn't work, I don't know.

**Pull request merged**
